pr:
  branches:
    include:
    - master
trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    set -Eeuxo pipefail
    cd tools
    npm install
  displayName: 'Install packages'
- script: |
    set -Eeuxo pipefail
    cd tools
    npm run test-ci
  displayName: 'Run schema tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'tools/test-results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'