pr: none
trigger: none

schedules:
- cron: "0 6 * * 5"
  branches:
    include:
    - master
  displayName: Weekly report of onboarded RPs

jobs:
- job: Generate
  timeoutInMinutes: 180

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    clean: true

  - task: DownloadSecureFile@1
    name: schemasDeployKey
    inputs:
      secureFile: schemas_rsa
    displayName: "Download GitHub Deploy Key"
  
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - script: |
      set -Eeuxo pipefail
      mkdir ~/.ssh && mv $(schemasDeployKey.secureFilePath) ~/.ssh/schemas_rsa
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/schemas_rsa
      git config user.name "Autogenerator Pipeline"
      git config user.email "azure-resource-manager-schemas@noreply.github.com"
      git config core.sshCommand "ssh -i ~/.ssh/schemas_rsa -F /dev/null"
      git remote set-url origin git@github.com:Azure/azure-resource-manager-schemas.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git fetch
    displayName: Configure git

  - script: |
      set -Eeuxo pipefail
      git checkout $(Build.SourceBranchName)
    displayName: Checkout repo

  - script: |
      set -Eeuxo pipefail
      cd generator
      npm install
    displayName: 'Install packages'

  - script: |
      set -Eeuxo pipefail
      cd generator
      npm run generate-onboarded-report
    displayName: 'Generate report'

  - script: |
      set -Eeuxo pipefail
      git add --all onboarded-report
      if ! git diff-index --quiet HEAD --; then
        git commit -m "Generated report"
        git push origin $(Build.SourceBranchName)
      fi
    displayName: Commit report