pr: none

schedules:
- cron: "0 8 * * *"
  branches:
    include:
    - autogenerate
  displayName: Daily autogeneration

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true
- script: |
    set -Eeuo pipefail
    git config user.name "Autogenerator Pipeline"
    git merge --strategy-option=theirs --no-ff -m "Integrate master" origin/master
    git checkout origin/master -- schemas
  displayName: Integrate master branch
- script: |
    set -Eeuo pipefail
    cd generator
    npm install
    npm run generate-all
    cd ..
  displayName: Generate schemas
- script: |
    set -Eeuo pipefail
    git config user.name "Autogenerator Pipeline"
    git add --all schemas
    if ! git diff-index --quiet HEAD --; then
      git commit -m "Autogenerate schemas"
      git push origin autogenerate
    fi
  displayName: Push changes to autogenerate branch