// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Immutable;
using System.Text.Json.Nodes;
using Azure.Bicep.Types.Concrete;

namespace TemplateSchemaGenerator;

public static class AutogeneratedResourcesGenerator
{
    private const string Draft04Schema = "http://json-schema.org/draft-04/schema#";

    public record ResourceRef(string ApiVersion, string ProviderNamespace, ResourceType ResourceType, string DefinitionKey);

    public static JsonNode Generate(ImmutableArray<ResourceRef> resourceRefs)
    {
        var root = new JsonObject
        {
            ["id"] = "https://schema.management.azure.com/schemas/common/autogeneratedResources.json#",
            ["title"] = "Azure Resource Schemas",
            ["description"] = "List of resource schemas grouped by scope",
            ["$schema"] = Draft04Schema,

            ["resourceGroup"] = BuildRefs(resourceRefs, ScopeType.ResourceGroup),
            ["subscription"] = BuildRefs(resourceRefs, ScopeType.Subscription),
            ["managementGroup"] = BuildRefs(resourceRefs, ScopeType.ManagementGroup),
            ["tenant"] = BuildRefs(resourceRefs, ScopeType.Tenant),
            ["unknown"] = BuildRefs(resourceRefs, ScopeType.None),
        };

        return root;
    }

    private static JsonArray BuildRefs(IEnumerable<ResourceRef> resourceRefs, ScopeType targetScope)
        => new(resourceRefs
            .Where(x => JsonSchemaGenerator.HasWritableScope(x.ResourceType, targetScope))
            .OrderBy(x => x.ProviderNamespace, StringComparer.OrdinalIgnoreCase)
            .ThenBy(x => x.ApiVersion, StringComparer.OrdinalIgnoreCase)
            .ThenBy(x => x.DefinitionKey, StringComparer.OrdinalIgnoreCase)
            .Select(x => ToRef(x, targetScope))
            .ToArray());

    private static JsonObject ToRef(ResourceRef resourceRef, ScopeType targetScope)
    {
        var section = targetScope switch
        {
            ScopeType.Tenant => JsonSchemaGenerator.TenantScopeResourceDefinitionsKey,
            ScopeType.ManagementGroup => JsonSchemaGenerator.ManagementGroupScopeResourceDefinitionsKey,
            ScopeType.Subscription => JsonSchemaGenerator.SubscriptionScopeResourceDefinitionsKey,
            ScopeType.ResourceGroup => JsonSchemaGenerator.ResourceGroupScopeResourceDefinitionsKey,
            ScopeType.None => JsonSchemaGenerator.UnknownScopeResourceDefinitionsKey,
            _ => throw new InvalidOperationException($"Unsupported scope type {targetScope}."),
        };

        return new JsonObject
        {
            ["$ref"] = $"https://schema.management.azure.com/schemas/{resourceRef.ApiVersion}/{resourceRef.ProviderNamespace}.json#/{section}/{resourceRef.DefinitionKey}",
        };
    }
}
