// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.CommandLine;
using System.Diagnostics;
using System.IO.Abstractions;

namespace TemplateSchemaGenerator;

internal static class Program
{
    public static async Task<int> Main(string[] args)
    {
        var sourceFolderOption = new Option<string>("--source-folder") { Required = true, Description = "The path to the 'generated' folder in the bicep-types-az repo" };
        var outputFolderOption = new Option<string>("--output-folder") { Required = true, Description = "The path to the output folder" };
        var providerNamespaceOption = new Option<string?>("--provider-namespace") { Description = "The provider namespace to generate" };
        var noUpdateRootSchemasOption = new Option<bool>("--no-update-root-schemas") { Description = "Skip updating the autogeneratedResources.json file" };
        var verboseOption = new Option<bool>("--verbose") { Description = "Enable verbose tracing" };

        var rootCommand = new RootCommand("ARM JSON schema generator")
        {
            sourceFolderOption,
            outputFolderOption,
            providerNamespaceOption,
            noUpdateRootSchemasOption,
            verboseOption,
        };

        rootCommand.SetAction((parseResult) =>
        {
            var sourceFolder = parseResult.GetValue(sourceFolderOption)!;
            var outputFolder = parseResult.GetValue(outputFolderOption)!;
            var providerNamespace = parseResult.GetValue(providerNamespaceOption);
            var noUpdateRootSchemas = parseResult.GetValue(noUpdateRootSchemasOption);
            var verbose = parseResult.GetValue(verboseOption);

            if (verbose)
            {
                Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
            }

            FileSystem fileSystem = new();
            MainGenerator generator = new(fileSystem, new(fileSystem, sourceFolder));
            generator.Generate(new(outputFolder, providerNamespace, !noUpdateRootSchemas));
        });

        return await rootCommand.Parse(args).InvokeAsync();
    }
}
