## ===========================================================================
# constants
$generatorRoot = ResolvePath "$PSScriptRoot/.."
$tmpRoot = ResolvePath ([IO.Path]::GetTempPath())

$restSpecsRepoPath = ResolvePath "$tmpRoot/schm_azspc"
$restSpecsRepoUri = "https://github.com/azure/azure-rest-api-specs"
$restSpecsRepoCommitHash = "origin/master"

$autoRestVerboseOutput = $false

$schemasBaseUri = "https://schema.management.azure.com/schemas"
$schemasBasePath = ResolvePath "$generatorRoot/../schemas"
$generatedSchemasUri = "$schemasBaseUri/2019-04-01/autogeneratedResources.json"
$generatedSchemasPath = ResolvePath "$schemasBasePath/2019-04-01/autogeneratedResources.json"
$generatedSchemasTemplatePath = ResolvePath "$generatorRoot/resources/autogeneratedResources_template.json"

# Run "npm run list-readmes" to discover all the valid readme files to add to this list
$whitelist  = @(
  'sqlvirtualmachine/resource-manager';
  'machinelearningcompute/resource-manager';
  'iotspaces/resource-manager';
  'botservice/resource-manager';
  'databox/resource-manager';
  'windowsiot/resource-manager';
  'databricks/resource-manager';
  'storagesync/resource-manager';
  'devspaces/resource-manager';
  'policyinsights/resource-manager';
  'servicefabricmesh/resource-manager';
  'labservices/resource-manager';
  'EnterpriseKnowledgeGraph/resource-manager';
  'edgegateway/resource-manager';
  'portal/resource-manager';
  'cosmos-db/resource-manager';
);