## ===========================================================================
# constants
$generatorRoot = Resolve-Path "$PSScriptRoot/.."
$tmpRoot = Resolve-Path ([IO.Path]::GetTempPath())

$restSpecsRepoPath = "$tmpRoot/schm_azspc"
$restSpecsRepoUri = "https://github.com/azure/azure-rest-api-specs"
$restSpecsRepoCommitHash = "origin/master"

$autoRestVerboseOutput = $false

$schemasBaseUri = "https://schema.management.azure.com/schemas"
$schemasBasePath = "$generatorRoot/../schemas"
$generatedSchemasUri = "$schemasBaseUri/2019-04-01/autogeneratedResources.json"
$generatedSchemasPath = "$schemasBasePath/2019-04-01/autogeneratedResources.json"
$generatedSchemasTemplatePath = "$generatorRoot/resources/autogeneratedResources_template.json"

# Run "npm run list-readmes" to discover all the valid readme files to add to this list
$whitelist  = @(
  'policyinsights/resource-manager';
);