// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
import { SchemaPostProcessor } from '../models';
import { replaceCyclicRefByName } from './helpers';

export const postProcessor: SchemaPostProcessor = async (namespace, apiVersion, schema) => {
  replaceCyclicRefByName(schema, 'ReportConfigFilter', { type: 'object' });
  replaceCyclicRefByName(schema, 'ReportFilter', { type: 'object' });
  replaceCyclicRefByName(schema, 'QueryFilter', { type: 'object' });
  replaceCyclicRefByName(schema, 'QueryFilterAutoGenerated', { type: 'object' });
  replaceCyclicRefByName(schema, 'Scope', { type: 'object' });
}